name: mahsa_park
description: A Flutter app to track car check-in, check-out, and payment status based on the license plate number.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  cloud_firestore: ^4.3.0
  provider: ^6.0.4
  url_launcher: ^6.2.6
url_launcher: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.3.3
  flutter_driver:
    sdk: flutter
  test: ^1.20.1

flutter:
  uses-material-design: true
  

# Assets and other settings can be defined here.
